### PR TITLE
fix: Do not automatically remove unmatched start/end directives when fixing.

### LINKED ISSUE #50: keep-sorted's handling of unmatched directives is a little awkward
https://github.com/google/keep-sorted/blob/bac77d0c1cffd305d3bc17666616deacfc7fac4c/keepsorted/keep_sorted.go#L143-L154

If we find a `keep-sorted start` or `keep-sorted end` line that don't have a corresponding `keep-sorted end` or `keep-sorted start` line, we recommend that it be deleted. That's certainly one way to solve the problem, but the other way to solve it would be to add the required directive somewhere else in the file.

Internal users have often run afoul of this especially with code templates that want the result to use keep-sorted, but the code template itself is using keep-sorted incorrectly.

The main problem they run into is that running keep-sorted in fix mode eagerly removes these lines without any prompting, which can be pretty frustrating. I think we should have some better behavior here so that the tool is a little less annoying to use

Some ideas:

  - `--mode=fix` should not automatically remove unmatched directives. It could instead log a warning
  - I think it'd still be useful for the findings to recommend the unmatched directives be removed (that way there's an easy fix in our review tool if they do want to remove the line)
  - I'm questioning whether we want to try and sort _anything_ if there are unmatched directives. There's a pretty good chance we'll construct blocks that are unintended, and sorting would be pretty destructive  (maybe just if there are unmatched start directives?). Perhaps we want to only report that there are unmatched directives, and let the user clean that up first before sorting anything

### PR DESCRIPTION
**Pull request by JeffFaer**
Still raise them in a lint warning, though.

Also, having an unmatched start/end directive likely means that the blocks we _do_ have are just straight up wrong. Stop trying to sort them automatically.

Fixes #50

### CODE REVIEW

File: keepsorted/keep_sorted_test.go [hunk 1]
```diff
@@ -179,8 +180,8 @@ foo
 			if gotAlreadyFixed != tc.wantAlreadyFixed {
 				t.Errorf("alreadyFixed diff: got %t want %t", gotAlreadyFixed, tc.wantAlreadyFixed)
 			}
-			if len(gotWarnings) != 0 {
-				t.Errorf("Fix returned warnings, expected none:\n%v", gotWarnings)
+			if diff := cmp.Diff(tc.wantWarnings, messages(gotWarnings), cmpopts.EquateEmpty()); diff != "" {
```
Comment (KatrinaHoffert) [inline keepsorted/keep_sorted_test.go:183]: Nit: r.e., cmpopts.EquateEmpty, what do you think of just making `messages()` use nil slices? Rationale: https://google.github.io/styleguide/go/decisions#nil-slices. Not like the utterly minor performance optimization of allocating the slice size perfectly makes any difference in a test.

**Review by KatrinaHoffert — APPROVED** [review]

File: keepsorted/keep_sorted_test.go (hunk 1 above)
Comment (JeffFaer) [reply keepsorted/keep_sorted_test.go:183]: Done
